# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# vagrant up; vagrant rsync-auto
#

require_relative 'conf/env.rb'
include MyEnv

Vagrant.configure("2") do |config|


  config.vm.define "haproxy" do |haproxy|
    haproxy.vbguest.auto_update = false
    haproxy.vm.box = "generic/alpine310"
    haproxy.vm.hostname = "haproxy"
    haproxy.vm.network "private_network", ip: "192.168.200.200"
    haproxy.vm.provision "shell", inline: <<-SHELL
      cd /vagrant
      ./scripts/haproxy.sh
    SHELL
    haproxy.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    haproxy.vm.provider :virtualbox do |vb|
          #vb.gui = true
          #vb.name = HOSTNAME
          vb.memory = 128
          vb.cpus = 1
          vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
          vb.customize ["modifyvm", :id, "--ioapic", "on"]
          vb.customize ["modifyvm", :id, "--description", "balancer node"]
          vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
        end
  end

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  config.vm.define "master" do |master|
    master.vm.box = "linux-k8s"
    master.vm.hostname = "kube-master"
    master.vm.network "private_network", ip: "192.168.200.100"
    master.vm.provision "shell", inline: <<-SHELL
      curl -sL https://raw.githubusercontent.com/theprotos/cookbooks-generic/development/scripts/linux.sh | sudo bash -s apply linux-k8s.json development
      cd /vagrant
      ./scripts/master-calico.sh
      ./scripts/master.sh
    SHELL
    master.vm.ignore_box_vagrantfile = true
    master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    master.vm.provider :virtualbox do |vb|
      #vb.gui = true
      #vb.name = HOSTNAME
      vb.memory = 2048
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
      vb.customize ["modifyvm", :id, "--description", "k8s master node"]
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
    end
  end

# Max 9 workers
  (1..2).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "linux-k8s"
      node.vm.hostname = "kube-node#{i}"
      node.vm.network "private_network", ip: "192.168.200.10#{i}"
      node.vm.provision "shell", inline: <<-SHELL
        curl -sL https://raw.githubusercontent.com/theprotos/cookbooks-generic/development/scripts/linux.sh | sudo bash -s apply linux-k8s.json development
        cd /vagrant
        ./scripts/worker.sh
      SHELL
      node.vm.ignore_box_vagrantfile = true
      node.vm.synced_folder ".", "/vagrant", type: "virtualbox"
      node.vm.provider :virtualbox do |vb|
        #vb.gui = true
        #vb.name = HOSTNAME
        vb.memory = 2048
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--description", "k8s worker node"]
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
      end
    end
  end
end