#
# Get OS images from https://github.com/theprotos/env-generic.git
#

Vagrant.configure("2") do |config|

if Vagrant.has_plugin?("vagrant-vbguest")
  config.vbguest.auto_update = false
end

  config.vm.define "node1" do |node1|
    node1.vm.box = "centos/8"
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", ip: "192.168.200.200"
###  vagrant up; vagrant rsync-auto
#    node1.vm.synced_folder ".", "/vagrant",
#        type: "rsync",
#        rsync__auto: true,
#        rsync__exclude: ['Vagrantfile'],
#        rsync__args: ["-z"]
    #node1.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    node1.vm.provision "shell", inline: <<-SHELL
      yum install -y yum-utils libseccomp-devel
      yum-config-manager \
          --add-repo \
          https://download.docker.com/linux/centos/docker-ce.repo
      yum install -y docker-ce docker-ce-cli containerd.io
      #curl -fsSL https://get.docker.com -o get-docker.sh && sh ./get-docker.sh && systemctl start docker
      systemctl start docker
      groupadd docker
      usermod -aG docker vagrant
    SHELL
  end
end
